language: android
before_install:
- nvm install 7
- node --version
install:
- yarn
android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - addon-google_apis-google-16
script: 
- npm run lint
- npm test
- cd android && ./gradlew assembleRelease
